### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by nestaval** [Crynners/AccBot#12]
Hi,

I miss release notes.
I am running v1.0.56 and now the latest release is v1.0.71.
However there is not provided a description of new features, bug fixes etc.
So I am not clear if it makes sense for me to upgrade or not.

Can you please start sharing the release notes with the new releases?

Thanks

**Comment by Crynners** [comment]
Hello nestaval,
thanks a lot for the feedback, you're right, the release notes should contain more comprehensive information. We will definitely work on this and the next release will contain more information than before. :)
Regarding new features, support for multiple exchanges (Huobi, Kraken, Binance and FTX) has been implemented. We also extended the logging with some additional information, addressed in issue #5 and #6.

Anyway, there were no critical features, it's not really necessary to update.

Regards,
Crynners
